%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '28px' }}}%%
sequenceDiagram
    actor User as 用户
    participant FE as 前端
    participant Ctrl as WorkHourController
    participant Svc as WorkHourServiceImpl
    participant Cache as Redis
    participant OrgM as OrgMapper
    participant EmpM as EmpBaseinfoMapper
    participant WHM as WorkHourMapper
    participant DB as MySQL

    User->>FE: 选择年月/组织，点击查询
    FE->>Ctrl: 请求 /workhour/bu-stat
    Ctrl->>Svc: 获取统计数据
    Svc->>Cache: 查询缓存
    
    alt 缓存命中
        Cache-->>Svc: 返回缓存数据
        Svc-->>Ctrl: 
        Ctrl-->>FE: 
        FE-->>User: 渲染BU分布饼图
    else 缓存未命中
        Cache-->>Svc: null
        
        Svc->>OrgM: 获取组织所有子孙节点
        OrgM->>DB: 
        DB-->>OrgM: 
        OrgM-->>Svc: orgIdList

        Svc->>EmpM: 查询员工UID列表
        EmpM->>DB: 
        DB-->>EmpM: 
        EmpM-->>Svc: uidList

        Svc->>WHM: 查询投入BU工时分布(startDate,endDate,uidList)
        WHM->>DB: 执行分组聚合查询
        DB-->>WHM: 
        WHM-->>Svc: 统计数据
        
        Svc->>Cache: 写入缓存(带过期时间)
        Svc-->>Ctrl: 
        Ctrl-->>FE: 
        FE-->>User: 渲染BU分布饼图
    end

##########################################################################
%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '28px' }}}%%
sequenceDiagram
    actor User as 用户
    participant FE as 前端
    participant Ctrl as WorkHourController
    participant Svc as WorkHourServiceImpl
    participant Cache as Redis

    participant PrjM as ProjectBaseinfoMapper
    participant WHM as WorkHourMapper
    participant DB as MySQL

    User->>FE: 点击饼图中的某个BU模块
    FE->>Ctrl: 请求 /workhour/bu-detail
    Ctrl->>Svc: 
    Svc->>Cache: 查询详情缓存
    
    alt 缓存命中
        Cache-->>Svc: 返回缓存数据
        Svc-->>Ctrl: 
        Ctrl-->>FE: 
        FE-->>User: 渲染详细信息与折线图
    else 缓存未命中
        Cache-->>Svc: null
        
        Svc->>PrjM: 获取该BU下所有项目ID
        PrjM->>DB: 
        DB-->>PrjM: 
        PrjM-->>Svc: projectIds

        Svc->>WHM: 查询考勤加班记录和近六个月趋势
        WHM->>DB: 
        DB-->>WHM: 
        WHM-->>Svc: 详情与趋势数据

        Svc->>Cache: 写入缓存
        Svc-->>Ctrl: 
        Ctrl-->>FE: 
        FE-->>User: 渲染详细信息与折线图
    end