@startuml
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
left to right direction

    class BugPageQueryStrategyFactory {
        - strategyMap : Map<String, BugPageQueryStrategy>
        + BugPageQueryStrategyFactory(strategies : List<BugPageQueryStrategy>)
        + getStrategy(source : String) : BugPageQueryStrategy
    }

    interface BugPageQueryStrategy {
        + getSource() : String
        + pageQuery(request : BugQueryRequest) : IPage
    }

    abstract class AbstractBugPageQueryStrategy<T> {
        # doPageQuery(request : BugQueryRequest) : IPage
        # buildWrapper(request : BugQueryRequest) : QueryWrapper<T>
        # applyFilterToWrapper(wrapper : QueryWrapper<T>, filter : Filter) : void
    }

    class TrinityBugPageQueryStrategy {
        + getSource() : String
        + pageQuery(request : BugQueryRequest) : IPage
    }

    class JiraBugPageQueryStrategy {
        + getSource() : String
        + pageQuery(request : BugQueryRequest) : IPage
    }

    class BugClosePageQueryStrategy {
        + getSource() : String
        + pageQuery(request : BugQueryRequest) : IPage
    }

BugPageQueryStrategyFactory o--> BugPageQueryStrategy : 注册和维护策略集合

BugPageQueryStrategy <|.. AbstractBugPageQueryStrategy
AbstractBugPageQueryStrategy <|-- TrinityBugPageQueryStrategy
AbstractBugPageQueryStrategy <|-- JiraBugPageQueryStrategy
AbstractBugPageQueryStrategy <|-- BugClosePageQueryStrategy

@enduml